version: '3.8'

services:
  postgres:
    image: docker.io/postgres:17
    environment:
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: example_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  spring:
    image: docker.io/eclipse-temurin:21-jdk
    working_dir: /app
    volumes:
      - gradle_cache:/root/.gradle
      - .:/app
    command: ./gradlew --no-daemon bootRun
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/example_db'
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  vite:
    image: docker.io/node:24-slim
    working_dir: /app
    volumes:
      - yarn_cache:/usr/local/share/.cache/yarn
      - ./src/main/front:/app
    command: [ "sh", "./start-server", "-u", "http://spring:8080" ]
    ports:
      - "5173:5173"

volumes:
  yarn_cache:
  gradle_cache:
  postgres_data:
